### ISSUE TITLE
Lua scripting ideas (TODO/WISH list)

### ISSUE THREAD

**Issue by adriweb** [CE-Programming/CEmu#252]
https://github.com/CE-Programming/CEmu/issues/19 is the issue for Lua scripting support in itself, but here's one for throwing some ideas about the Lua integration/features in CEmu, so basically a TODO/WISH list:

GUI:
* [ ] **Listing available scripts**.  We probably need a `scripts` folder in the CEmu appdata one.
* [ ] **Autoloading some scripts**.  Let the user autoload some script at some point (when should that happen?)
* [ ] **Setting to enable unsafe functions**.  The `require`, `loadfile`, `dofile` functions and the `io`, `os`, `debug` modules are currently disabled by default for safety reasons.

Developer:
* [ ] **Generic events/hooking system**. User callback will be fired when something specific happens.
* [ ] **Example useful scripts**.  Shipped by default with CEmu
* [ ] **Tutorial/Docs**.  That's probably useful...

Bindings:
* [ ] **Disasm APIs bindings**. Use zdis correctly.
* [ ] **More GUI bindings**. All existing GUI stuff should have a Lua equivalent

Other:
* [ ] **GitHub repo of Lua scripts**.  To have a shared area of scripts user can download in CEmu.
* [ ] **CLI arguments stuff**. Should probably have some things to launch a script at boot or something

**Comment by adriweb** [comment]
This has now been finalized, at least in a state that implements almost all of the todo/wish list above, and some more things that have since been added to the core and/or GUI and made sense to bind to Lua.

Here is what's now available _(credits to Codex for adding more bindings, docs, and tutorials :P)_

<img width="3306" height="2382" alt="Image" src="https://github.com/user-attachments/assets/da1fa680-bdfd-4568-9a33-7fcdb942a7a2" />

## GUI and runtime

* [x] **Script manager and scripts directory**. CEmu has a Scripts tab backed by a `scripts` directory beside the active configuration file.
* [x] **Bundled scripts**. Examples are installed into the scripts directory without overwriting locally modified copies.
* [x] **Script autoloading**. Scripts can be checked for autoload and are executed in filename order after the emulator is initialized.
* [x] **Unsafe-library setting**. Trusted scripts can enable `require`, `loadfile`, `dofile`, `package`, `io`, `os`, and Lua's standard `debug` module.
  * CEmu debugger functions use the separate `dbg` table, leaving `debug` available for its standard Lua meaning.
  * Changing this setting safely restarts active Lua states.
* [x] **Global opt-in/lazy runtime**. Lua is disabled by default and no Lua state is created during ordinary emulation.
  * It is enabled when requested by an autoload script, `--lua-script`, IPC, the editor, the REPL, or the session toggle.
  * Disabling Lua runs cleanup callbacks, removes timers and event handlers, and destroys the Lua states.
  * Events without subscribers avoid Lua dispatch and payload construction.
* [x] **Built-in script editor**.
  * File open/save/run workflow.
  * Correctly sized line-number gutter.
  * Dark-mode-aware editor, gutter, selection, and syntax colors.
  * Lua syntax highlighting and automatic indentation.
  * Global and table-member completion suggestions, including explicit completion with Ctrl+Space.
* [x] **REPL**. The REPL uses a state separate from the script editor/autoload runtime.
* [x] **Script lifecycle controls**. Scripts can register unload handlers, clean themselves up, stop cooperatively, and reload themselves.

## Events and scheduling

* [x] **Generic event/hooking system** using `cemu.on()` and `cemu.off()`.
* [x] **Filterable event handlers**.
  * Exact-field filters, `where`, predicates, and one-shot handlers.
  * Registration-order dispatch.
  * Per-state event sequence numbers and common timing/PC metadata.
* [x] **Emulator lifecycle events** for startup, load, reset, and script loading.
* [x] **Input and frame events**.
* [x] **Debugger events** for breakpoints, watchpoints, register access, and peripheral access.
* [x] **TI-BASIC debugger events** for stepping, source breakpoints, and watched-variable changes.
* [x] **Transfer events** for start, progress, completion, failure, and cancellation.
* [x] **Conditional breakpoints** from [#265](https://github.com/CE-Programming/CEmu/issues/265).
  * Breakpoint/watchpoint callbacks can inspect emulator state.
  * Returning `false` suppresses the debugger stop and resumes emulation.
* [x] **Virtual-time scheduling**.
  * Millisecond- and CPU-cycle-based one-shot/repeating callbacks.
  * Timer cancellation and automatic state-scoped cleanup.

## Core and debugger bindings

* [x] **CPU state**. eZ80 registers, flags, execution state, and cycle information are exposed.
* [x] **Memory access**.
  * Byte/short/long/word reads and writes.
  * Efficient block reads/writes.
  * Fill, copy, search, and CRC-32 operations.
* [x] **All core peripheral ranges and registers**.
  * Direct `peek`/`poke` access to the complete 16-bit peripheral address space.
  * CPU-style timed reads/writes with normal side effects.
  * Named peripheral ranges, snapshots, descriptions, and monitor/freeze state.
* [x] **Debugger controls**.
  * Stop/resume and the normal stepping operations.
  * Breakpoint and watchpoint creation/removal.
  * Register watches and peripheral monitors.
  * Coherent snapshots of debugger configuration and CPU registers.
* [x] **Disassembly API** using zdis.
  * Instruction bytes, size, opcode, operands, formatted text, and next address.
  * Current-PC disassembly.
* [x] **Symbols/equates**.
  * Load equate files.
  * Enumerate and resolve symbols.
  * Perform address-to-symbol lookups.

## Calculator and variable bindings

* [x] **Live calculator VAT access** through `vars`.
  * List and find variables by name/type.
  * Read raw calculator storage.
  * Launch programs through the normal calculator/UI path.
* [x] **High-level host-side variable creation** through `tivars_lib_cpp`.
  * Create variables by type name or numeric type ID.
  * Select a calculator model or default to CEmu's active model.
  * Set readable or raw content.
  * Tokenize and detokenize TI-BASIC programs.
  * Change variable name and Archive state.
  * Serialize to a complete calculator file or save it to disk.
  * Transfer a generated variable directly to RAM or Archive.
  * Enumerate supported models and types.
* [x] **Transfer controls**.
  * Send existing or generated files.
  * Select RAM, Archive, or automatic placement.
  * Inspect status/progress and request cancellation.
  * Automatically remove temporary generated files after completion or failure.

## LCD and screen bindings

* [x] **LCD controller state** equivalent to the PL111 debugger information.
* [x] **LCD panel/driver state** equivalent to the ST7789 debugger information.
  * Register/parser state, address windows, scrolling, pixel formats, timing, modes, and gamma curves.
* [x] **LCD panel commands** through the real parser and side-effect path.
* [x] **Useful LCD debugger-pane operations**, including showing, refreshing, and applying pane state.
* [x] **Screen settings** such as DMA, gamma, response, scaling, upscaling, and skin.
* [x] **Framebuffer inspection**.
  * Complete RGBA/RGB frames and cropped regions.
  * Pixel reads and color comparisons.
  * Frame metadata and CRC-32 hashes suitable for assertions.

## TI-BASIC debugging

* [x] **Source-level debugger controls**.
  * Enable/show the debugger and inspect its current state.
  * Step, step-next, and resume.
  * Add/remove source-line breakpoints.
* [x] **TI-BASIC source access** and the same source preparation/deindentation used by the editable variable previewer.
* [x] **Variable-change watches** and corresponding events.
* [x] **Debugger display options**, including fetches, temporary parser state, highlighting, and live execution.

## Emulator, GUI, and automation bindings

* [x] **Script-relevant GUI operations**.
  * Screenshots, status messages, message boxes, refresh, fullscreen, keypad color, scripts-folder access, and quit.
* [x] **Emulator controls**.
  * Reset, ROM reload, speed/throttling, device information, state save/load, and emulated-time queries.
* [x] **Input automation**.
  * Press/down/up/hold operations.
  * Timed key sequences.
* [x] **TAS workflow support** from [#275](https://github.com/CE-Programming/CEmu/issues/275).
  * Known-state loading, virtual-time scheduling, deterministic input, screenshots, framebuffer checks, and state checkpoints.
* [x] **Autotester integration** for loading, reloading, and launching existing JSON tests.

## Distribution and documentation

* [x] **Example useful scripts shipped with CEmu**. There are currently simple and advanced examples covering memory, variables, generated TI-BASIC programs, transfers, peripherals, LCD state, framebuffer assertions, debugging, events, cleanup, timers, conditional stops, and TAS-style input.
* [x] **Documentation** in `docs/lua-scripting.md`, including runtime safety, lifecycle, events, bindings, LCD access, TI-BASIC debugging, examples, TAS usage, and CLI usage.
* [x] **CLI script execution** through repeatable `--lua-script <path>` arguments.
  * Scripts run after initialization in command-line order.
  * Commands can also be forwarded to an existing CEmu instance through IPC.
